# Generated by Django 3.2.9 on 2021-12-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=5)),
                ('cpu_name', models.CharField(max_length=50)),
                ('code_name', models.CharField(default='', max_length=20)),
                ('cpu_base_clock', models.CharField(default='', max_length=10)),
                ('disk', models.CharField(max_length=500)),
                ('hostname', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=40)),
                ('bios_version', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=20)),
                ('memory_detail', models.CharField(default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('lab_name', models.CharField(default='', max_length=10)),
                ('rack_name', models.CharField(default='', max_length=30)),
                ('rack_position', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
