# Generated by Django 3.2.9 on 2021-12-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('cpu_name', models.CharField(max_length=50)),
                ('code_name', models.CharField(default='', max_length=20)),
                ('cpu_base_clock', models.CharField(default='', max_length=10)),
                ('disk', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('bios_version', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=50)),
                ('is_actve', models.BooleanField(default=True)),
                ('lab_name', models.CharField(default='', max_length=10)),
                ('rack_name', models.CharField(default='', max_length=30)),
                ('rack_position', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
