# Generated by Django 3.2.9 on 2021-12-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
    ]
