# Generated by Django 3.2.9 on 2021-12-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(max_length=100),
        ),
    ]
