# Generated by Django 3.2.9 on 2021-12-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20211215_0720'),
    ]

    operations = [
    ]
