# Generated by Django 3.2.9 on 2021-12-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='is_actve',
            new_name='is_active',
        ),
    ]
