# Generated by Django 3.2.9 on 2021-12-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_is_actve_host_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='memory_detail',
            field=models.CharField(default='', max_length=500),
        ),
    ]
