# Generated by Django 3.2.9 on 2021-12-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20211216_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='memory_detail',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
