# Generated by Django 3.2.9 on 2021-12-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_host_memory_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(max_length=500),
        ),
    ]
