# Generated by Django 3.2.9 on 2021-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_host_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(max_length=40),
        ),
    ]
